# Generated by Django 4.2.30 on 2026-09-04 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='asignatura',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('creditos', models.IntegerField()),
                ('horas_teoria', models.IntegerField()),
                ('horas_practica', models.IntegerField()),
                ('ciclo', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
                'db_table': 'asignatura',
            },
        ),
        migrations.CreateModel(
            name='aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'db_table': 'aula',
            },
        ),
        migrations.CreateModel(
            name='docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'db_table': 'docente',
            },
        ),
        migrations.CreateModel(
            name='estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_universitario', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=150)),
                ('ciclo_actual', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'estudiante',
            },
        ),
        migrations.CreateModel(
            name='grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(max_length=20)),
                ('seccion', models.CharField(max_length=10)),
                ('vacantes', models.IntegerField()),
                ('cupos_ocupados', models.IntegerField(default=0)),
                ('codigo', models.ForeignKey(db_column='codigo', on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='horarios.asignatura')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'db_table': 'grupo',
            },
        ),
        migrations.CreateModel(
            name='Periodo_Academico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'verbose_name': 'Periodo Académico',
                'verbose_name_plural': 'Periodos Académicos',
                'db_table': 'periodo_academico',
            },
        ),
        migrations.CreateModel(
            name='SolicitudAmpliacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditosAdicionales', models.IntegerField()),
                ('estado', models.CharField(max_length=20)),
                ('fechasolicitud', models.DateTimeField(auto_now_add=True)),
                ('id_estudiante', models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_ampliacion', to='horarios.estudiante')),
                ('id_periodo', models.ForeignKey(db_column='id_periodo', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_ampliacion', to='horarios.periodo_academico')),
            ],
            options={
                'verbose_name': 'Solicitud de Ampliación',
                'verbose_name_plural': 'Solicitudes de Ampliación',
                'db_table': 'solicitud_ampliacion',
            },
        ),
        migrations.CreateModel(
            name='seleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_seleccion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='confirmada', max_length=20)),
                ('id_asignatura', models.ForeignKey(db_column='id_asignatura', on_delete=django.db.models.deletion.CASCADE, related_name='selecciones', to='horarios.asignatura')),
                ('id_estudiante', models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.CASCADE, related_name='selecciones', to='horarios.estudiante')),
                ('id_grupo', models.ForeignKey(db_column='id_grupo', on_delete=django.db.models.deletion.CASCADE, related_name='selecciones', to='horarios.grupo')),
                ('id_periodo', models.ForeignKey(db_column='id_periodo', on_delete=django.db.models.deletion.CASCADE, related_name='selecciones', to='horarios.periodo_academico')),
            ],
            options={
                'verbose_name': 'Selección de Horario',
                'verbose_name_plural': 'Selecciones de Horarios',
                'db_table': 'seleccion',
            },
        ),
        migrations.CreateModel(
            name='Prerequisitos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura_codigo', models.ForeignKey(db_column='asignatura_codigo', on_delete=django.db.models.deletion.CASCADE, related_name='prerequisitos_de', to='horarios.asignatura')),
                ('asignatura_requisito', models.ForeignKey(db_column='asignatura_requisito', on_delete=django.db.models.deletion.CASCADE, related_name='requisito_para', to='horarios.asignatura')),
            ],
            options={
                'verbose_name': 'Prerrequisito',
                'verbose_name_plural': 'Prerrequisitos',
                'db_table': 'prerequisitos',
            },
        ),
        migrations.CreateModel(
            name='HistorialAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField()),
                ('estado', models.CharField(max_length=20)),
                ('id_asignatura', models.ForeignKey(db_column='id_asignatura', on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='horarios.asignatura')),
                ('id_estudiante', models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='horarios.estudiante')),
                ('id_periodo', models.ForeignKey(db_column='id_periodo', on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='horarios.periodo_academico')),
            ],
            options={
                'verbose_name': 'Historial Académico',
                'verbose_name_plural': 'Historiales Académicos',
                'db_table': 'historial_academico',
            },
        ),
        migrations.AddField(
            model_name='grupo',
            name='id_periodo',
            field=models.ForeignKey(db_column='id_periodo', on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='horarios.periodo_academico'),
        ),
        migrations.CreateModel(
            name='disponibilidad_aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(max_length=15)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('id_aula', models.ForeignKey(db_column='id_aula', on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='horarios.aula')),
                ('id_periodo', models.ForeignKey(db_column='id_periodo', on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades_aula', to='horarios.periodo_academico')),
            ],
            options={
                'verbose_name': 'Disponibilidad Aula',
                'verbose_name_plural': 'Disponibilidades Aula',
                'db_table': 'disponibilidad_aula',
            },
        ),
        migrations.CreateModel(
            name='bloque_horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(max_length=15)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('id_aula', models.ForeignKey(db_column='id_aula', on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='horarios.aula')),
                ('id_docente', models.ForeignKey(blank=True, db_column='id_docente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloques', to='horarios.docente')),
                ('id_grupo', models.ForeignKey(db_column='id_grupo', on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='horarios.grupo')),
            ],
            options={
                'verbose_name': 'Bloque Horario',
                'verbose_name_plural': 'Bloques Horarios',
                'db_table': 'bloque_horario',
            },
        ),
        migrations.AddConstraint(
            model_name='seleccion',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['pendiente', 'confirmada'])), fields=('id_estudiante', 'id_asignatura', 'id_periodo'), name='unique_active_seleccion_per_period'),
        ),
    ]
